// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfnHMkbvjJ86CS5AvPWxfh1fL3dhRvwDo',
    appId: '1:52052423413:web:921954b9ae4a1498f6cbbc',
    messagingSenderId: '52052423413',
    projectId: 'nildesapps',
    authDomain: 'nildesapps.firebaseapp.com',
    storageBucket: 'nildesapps.appspot.com',
    measurementId: 'G-1SNPJRG3V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wcGp_e52Av9LQetwqAgBdNdngv8FNOc',
    appId: '1:52052423413:android:c4f1216200e13f17f6cbbc',
    messagingSenderId: '52052423413',
    projectId: 'nildesapps',
    storageBucket: 'nildesapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8438qb1YhyArAXSIUEQQsH3h3Q8oFSRM',
    appId: '1:52052423413:ios:629b0df926efc875f6cbbc',
    messagingSenderId: '52052423413',
    projectId: 'nildesapps',
    storageBucket: 'nildesapps.appspot.com',
    iosClientId: '52052423413-19r13moifldq32t6vj1deosbk6sti93n.apps.googleusercontent.com',
    iosBundleId: 'com.example.nildesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8438qb1YhyArAXSIUEQQsH3h3Q8oFSRM',
    appId: '1:52052423413:ios:629b0df926efc875f6cbbc',
    messagingSenderId: '52052423413',
    projectId: 'nildesapps',
    storageBucket: 'nildesapps.appspot.com',
    iosClientId: '52052423413-19r13moifldq32t6vj1deosbk6sti93n.apps.googleusercontent.com',
    iosBundleId: 'com.example.nildesapp',
  );
}
